apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssl-test-cluster-stats-{{SANITIZED_SUBDOMAIN}}
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
