apiVersion: v1
kind: ServiceAccount
metadata:
  name: ssl-test-cluster-reader-{{SANITIZED_SUBDOMAIN}}
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ssl-test-cluster-reader-{{SANITIZED_SUBDOMAIN}}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ssl-test-cluster-reader-{{SANITIZED_SUBDOMAIN}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ssl-test-cluster-reader-{{SANITIZED_SUBDOMAIN}}
subjects:
- kind: ServiceAccount
  name: ssl-test-cluster-reader-{{SANITIZED_SUBDOMAIN}}
  namespace: default
