---
- name: Converge
  hosts: all
  become: yes
  vars:
    rke2_version: v1.33.3+rke2r1
    rke2_snapshotter: native
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
