---
- name: Converge
  hosts: all
  become: yes
  vars:
    # Uses role default rke2_version from defaults/main.yml
    rke2_snapshotter: native
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
