apiVersion: v1
kind: Pod
metadata:
  name: nvidia-runtime-test
spec:
  runtimeClassName: nvidia
  restartPolicy: Never
  nodeSelector:
    node-type: gpu-worker
  containers:
  - name: test
    image: nvidia/cuda:12.0-base-ubuntu20.04
    command: ["/bin/bash"]
    args:
    - -c
    - |
      echo "NVIDIA Container Toolkit Runtime Test"
      echo "===================================="
      echo "Container scheduled successfully with nvidia runtime!"
      echo "Runtime: nvidia"
      echo "Image: nvidia/cuda:12.0-base-ubuntu20.04"
      echo "Node: $(hostname)"
      echo "Test completed - nvidia runtime is working!"
      sleep 10
