---
# Copy this file to playbooks/proxmox-vars/lxc_map.yml and fill in the values.
# This file is intentionally safe to commit; the filled version should be git-ignored.

proxmox_cluster:
  template: /var/lib/vz/template/cache/ubuntu-24.04-standard_24.04-2_amd64.tar.zst
  bridge: vmbr0
  vlan_tag: 14
  gateway: 10.14.1.1
  mtu: 9000

  storage_defaults:
    zfs_pool: temp-pool         # default pool for zfs_volume mounts
    rootfs: local-lvm:60        # default rootfs storage

  ssh:
    username: adm4n             # container admin user to create
    password: password123         # set a strong password

  nvidia:
    driver_host_path: "/root/NVIDIA-Linux-x86_64-575.64.05.run"        # e.g., /root/NVIDIA-Linux-x86_64-575.64.05.run on the Proxmox host
    driver_dest_path: "/root"   # where to copy in the container
    driver_version: "575.64.05" # NVIDIA driver version number

  containers:
    - id: 101
      host: 10.0.10.8
      hostname: os-env-cp-1
      ip: 10.14.100.1/16
      memory: 16384
      cores: 8
      rootfs: local-lvm:60
      mounts:
        - type: storage
          storage: local-lvm
          name: vm-101-data
          size: 50G
          container_path: /mnt/data
      gpu: true

    - id: 102
      host: 10.0.10.7
      hostname: os-env-cpu-1
      ip: 10.14.100.2/16
      memory: 121072
      cores: 32
      rootfs: local-lvm:60
      mounts:
        - type: local-lvm
          name: vm-102-data
          size: 3T
          container_path: /mnt/data
      gpu: true

    - id: 103
      host: 10.0.10.5
      hostname: os-env-gpu-1
      ip: 10.14.100.3/16
      memory: 171072
      cores: 32
      rootfs: local-lvm:60
      mounts:
        - type: zfs_volume
          name: vm-103-data
          size: 3T
          container_path: /mnt/data
      gpu: true
