---

- name: Download RKE2 kubeconfig to localhost
  ansible.builtin.fetch:
    src: /etc/rancher/rke2/rke2.yaml
    dest: "{{ rke2_download_kubeconf_path }}/{{ rke2_download_kubeconf_file_name }}"
    flat: yes
  when:
  - rke2_download_kubeconf | bool
  - inventory_hostname == groups[rke2_servers_group_name].0

- name: Replace loopback IP by master server IP
  ansible.builtin.replace:
    path: "{{ rke2_download_kubeconf_path }}/{{ rke2_download_kubeconf_file_name }}"
    mode: '0600'
    regexp: '127.0.0.1'
    replace: "{{ rke2_api_ip | default(hostvars[groups[rke2_servers_group_name].0].ansible_host) }}"
  delegate_to: localhost
  become: false
  when:
  - not ansible_check_mode
  - rke2_download_kubeconf | bool
  - inventory_hostname == groups[rke2_servers_group_name].0

- name: Summary
  when: inventory_hostname == groups[rke2_servers_group_name].0
  block:
    - name: Prepare summary
      ansible.builtin.shell: |
        set -e
        {{ rke2_data_path }}/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get nodes -o wide --show-labels
      args:
        executable: /bin/bash
      changed_when: false
      retries: 5
      register: nodes_summary

    - name: K8s nodes state
      ansible.builtin.debug:
        var: nodes_summary.stdout_lines

    # Label GPU nodes for proper scheduling after cluster is ready
    - name: Label GPU nodes for Kubernetes scheduling
      ansible.builtin.shell: |
        echo "Labeling GPU nodes for proper scheduling..."
        
        # Label node 10.14.100.2 as GPU worker
        {{ rke2_data_path }}/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml label nodes 10.14.100.2 node-type=gpu-worker --overwrite
        {{ rke2_data_path }}/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml label nodes 10.14.100.2 nvidia.com/gpu.present=true --overwrite
        echo "SUCCESS: GPU node 10.14.100.2 labeled for GPU workloads"
        
        # Label node 10.14.100.3 as GPU worker  
        {{ rke2_data_path }}/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml label nodes 10.14.100.3 node-type=gpu-worker --overwrite
        {{ rke2_data_path }}/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml label nodes 10.14.100.3 nvidia.com/gpu.present=true --overwrite
        echo "SUCCESS: GPU node 10.14.100.3 labeled for GPU workloads"
        
        echo "GPU node labeling completed"
      args:
        executable: /bin/bash
      register: gpu_labeling_result
      changed_when: "'SUCCESS' in gpu_labeling_result.stdout"

    - name: Display GPU node labeling results
      ansible.builtin.debug:
        var: gpu_labeling_result.stdout_lines
      when: gpu_labeling_result is defined
